service: recontweeter

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1

functions:
  retweet:
    handler: retweet.retweet_random
    events:
      - schedule: rate(2 hours)
    timeout: 10
  popular:
    handler: retweet.retweet_most_popular
    events:
      - schedule: cron(30 9 ? * 6L *)
    timeout: 30

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
